[tool.mypy]
# Target the simplejwt package
files = "./simplejwt/rest_framework_simplejwt"
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]
exclude = [".*/migrations/[0-9]{4}_.*.py$"]
show_error_codes = true
# Be more strict
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
# Warn everyhing
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

[tool.django-stubs]
django_settings_module = "app.app.settings"  # in order to work from root
